# FROM node:14-alpine as builder
# WORKDIR /usr/src/app
# COPY package*.json ./

# RUN npm cache clean --force
# RUN npm config set registry http://registry.npmjs.org/
# RUN npm config set proxy http://registry.npmjs.org/
# RUN npm config set https-proxy http://registry.npmjs.org/

# RUN npm install
# COPY . .
# RUN npm run build

FROM nginx:alpine
#!/bin/sh
COPY ./nginx.conf /etc/nginx/nginx.conf
RUN rm -rf /usr/share/nginx/html/*
COPY build /usr/share/nginx/html

EXPOSE 80
VOLUME [ "/etc/nginx/" ]

ENTRYPOINT ["nginx", "-g", "daemon off;"]