export const RUN_VALUE_UPDATE: string = "RUN_VALUE_UPDATE";
export const TURN_VALUE_UPDATE: string = "TURN_VALUE_UPDATE";
export const SET_CHARGE_LEVEL: string = "SET_CHARGE_LEVEL";

export const RUN_VALUE_QUEST_UPDATE: string = "RUN_VALUE_QUEST_UPDATE";
export const SET_REQUEST_RUN_TRUE: string = "SET_REQUEST_RUN_TRUE";
export const SET_REQUEST_RUN_FALSE: string = "SET_REQUEST_RUN_FALSE";

export const TURN_VALUE_QUEST_UPDATE: string = "TURN_VALUE_QUEST_UPDATE";
export const SET_REQUEST_TURN_TRUE: string = "SET_REQUEST_TURN_TRUE";
export const SET_REQUEST_TURN_FALSE: string = "SET_REQUEST_TURN_FALSE";
export const SET_IS_DISCONNECTED: string = "SET_IS_DISCONNECTED";
export const SET_IS_TRANSLATED_VIDEO: string = "SET_IS_TRANSLATED_VIDEO";
export const SET_IS_INIT_GET_CHARGE: string = "SET_IS_INIT_GET_CHARGE";
