export const  RUN_VALUE_UPDATE = "RUN_VALUE_UPDATE"
export const  TURN_VALUE_UPDATE = "TURN_VALUE_UPDATE"
export const  SET_CHARGE_LEVEL = "SET_CHARGE_LEVEL"

export const  RUN_VALUE_QUEST_UPDATE = "RUN_VALUE_QUEST_UPDATE"
export const  SET_REQUEST_RUN_TRUE = "SET_REQUEST_RUN_TRUE"
export const  SET_REQUEST_RUN_FALSE = "SET_REQUEST_RUN_FALSE"

export const  TURN_VALUE_QUEST_UPDATE = "TURN_VALUE_QUEST_UPDATE"
export const  SET_REQUEST_TURN_TRUE = "SET_REQUEST_TURN_TRUE"
export const  SET_REQUEST_TURN_FALSE = "SET_REQUEST_TURN_FALSE"
export const  SET_IS_DISCONNECTED = "SET_IS_DISCONNECTED"
export const  SET_IS_TRANSLATED_VIDEO = "SET_IS_TRANSLATED_VIDEO"
export const  SET_IS_INIT_GET_CHARGE = "SET_IS_INIT_GET_CHARGE"
